import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from './navbar';
import Footer from './footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body className={inter.className}>
        <div className='w-full min-h-screen sm:px-[12%] px-[2%] sm:py-[4%] py-[10%]'>
          <Navbar/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  )
}
